// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBedImcnkc6qAdul93_nBNHsSBwkKIhLpg',
    appId: '1:26654271433:ios:b437b8995cf6e339f8ea18',
    messagingSenderId: '26654271433',
    projectId: 'quranepak-5b3c5',
    storageBucket: 'quranepak-5b3c5.firebasestorage.app',
    iosBundleId: 'com.example.quranepak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBedImcnkc6qAdul93_nBNHsSBwkKIhLpg',
    appId: '1:26654271433:ios:b437b8995cf6e339f8ea18',
    messagingSenderId: '26654271433',
    projectId: 'quranepak-5b3c5',
    storageBucket: 'quranepak-5b3c5.firebasestorage.app',
    iosBundleId: 'com.example.quranepak',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaQS80vk5AMBpa-ws4G7k3Mpz6MBj-ukY',
    appId: '1:26654271433:web:a80189445d9da0abf8ea18',
    messagingSenderId: '26654271433',
    projectId: 'quranepak-5b3c5',
    authDomain: 'quranepak-5b3c5.firebaseapp.com',
    storageBucket: 'quranepak-5b3c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-XrgeT_rcHvMUZyub-5oWgDTNrfcVq9w',
    appId: '1:26654271433:android:1cf6c3f5fa1d3b10f8ea18',
    messagingSenderId: '26654271433',
    projectId: 'quranepak-5b3c5',
    storageBucket: 'quranepak-5b3c5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaQS80vk5AMBpa-ws4G7k3Mpz6MBj-ukY',
    appId: '1:26654271433:web:5a799e23d3e0df02f8ea18',
    messagingSenderId: '26654271433',
    projectId: 'quranepak-5b3c5',
    authDomain: 'quranepak-5b3c5.firebaseapp.com',
    storageBucket: 'quranepak-5b3c5.firebasestorage.app',
  );

}